### PR TITLE
Fix image positioning

### PR DESCRIPTION
**Pull request by hoehooiyan**
#2 Fix bug in image positioning

### CODE REVIEW

**Comment by heytulsiprasad** [comment]
That's great the `align-self` really didn't belong there. It seems to work fine. However, do you seem to know what makes this extra space occur below the image when we reduce the horizontal viewport?
image

I saw, that is the `picture__box` div, which holds the image tag. I think we need to declare some kind of height for the div?

**Comment by heytulsiprasad** [comment]
Oh this fills the div with the image, great. 👍 

By the way, I think we shouldn't give the `grid-template-rows` fractional values, `1fr` as in this case, when the other layer (except the pictures) when gets compressed while changing the viewport, the height of `fr` increases and it makes the picture layer to get bigger to match with defination of `1fr`.

**Comment by hoehooiyan** [comment]
> Oh this fills the div with the image, great. 👍
> 
> By the way, I think we shouldn't give the `grid-template-rows` fractional values, `1fr` as in this case, when the other layer (except the pictures) when gets compressed while changing the viewport, the height of `fr` increases and it makes the picture layer to get bigger to match with defination of `1fr`.

That's right. Also, in order to make the layout responsive, maybe you can describe how you want it to be on a tablet or smaller phone? From that, we can get a more detailed requirement.

**Comment by heytulsiprasad** [comment]
Finally, #2 seems to be solved. I am going to make this responsive soon and make this cooler.

**Comment by heytulsiprasad** [comment]
> Also, in order to make the layout responsive, maybe you can describe how you want it to be on a tablet or smaller phone?

I think I am gonna use some js to remove the not being edited image in the mobile view, and also make the layer below the pictures look one below the other. What do you think? Lemme merge this PR, first. 

Btw, if you wanna add something sure, I can always put that up in a different branch!

**Pull request merged**
